### ISSUE TITLE
Form submission submits blank value for input in IE when hitting the enter key

### ISSUE THREAD

**Issue by toml0006** [thehappybit/jQuery-HTML5-placeholder-plugin#1]
It looks like adding an event handler to the input for keyup events when the enter key is pressed will fix the issue.

Tested in IE 8

Steps to reproduce:
1. On an input with the placeholder plugin activated, enter a value of "foo"
2. While still focused on the input, press the enter key (submitting the form)
3. Observe that the form is submitted with the empty string for that input ("foo" is expected)

**Comment by thehappybit** [comment]
Hi there,  

your modification to add support for the ENTER key in a placeholder input has been merged to the main branch. Thanks, much appreciated! :)  

## 

The Happy Bit – http://thehappybit.com
Skype: thehappybit
Twitter: @thehappybit
Dribbble: @thehappybit

Simone Maranzana: (+39) 328 7346305
Andrea Gandino: (+39) 348 4694450

Il giorno giovedì 2 agosto 2012, alle ore 18:15, Jackson Tomlinson ha scritto:
